module:
  name: { module_name }
  title: { module_title }
  description: { module_description }
  version: 1.0.0

installation:
  required: false
  dependencies: []

  questions:
    - name: confirm_install
      prompt: Install {module_title}?
      type: confirm
      default: true

platform_specifics:
  claude_code:
    enabled: true
  windsurf:
    enabled: true
  cursor:
    enabled: true
  cline:
    enabled: true
  qwen:
    enabled: true

components:
  agents:
    - source: agents/
      destination: "{module_name}/agents/"

  workflows:
    - source: workflows/
      destination: "{module_name}/workflows/"
