workflow:
  name: Assess Project Scale
  description: Determine project complexity level (0-4) through interactive Q&A
  version: 1.0.0
  module: mam
  type: planning

  steps:
    - name: Welcome and Overview
      type: guide
      content: |
        # Project Scale Assessment

        This workflow will help determine your project's complexity level:
        - **Level 0**: Simple task (1-2 hours, single file/function)
        - **Level 1**: Feature addition (2-8 hours, 2-5 files)
        - **Level 2**: Small project (1-3 days, 5-15 files, single epic)
        - **Level 3**: Medium project (1-2 weeks, 15-40 files, 2-5 epics)
        - **Level 4**: Large project (2+ weeks, 40+ files, 5+ epics)

        Let's determine your project's scale level.

    - name: Gather Project Basics
      type: elicit
      prompts:
        - key: project_name
          question: What is your project name?
          required: true
        - key: project_description
          question: Briefly describe your project (1-2 sentences)
          required: true

    - name: Assess Scope
      type: elicit
      prompts:
        - key: time_estimate
          question: How long do you estimate this will take?
          options:
            - 1-2 hours
            - 2-8 hours
            - 1-3 days
            - 1-2 weeks
            - 2+ weeks
          required: true
        - key: file_count_estimate
          question: Approximately how many files will be created/modified?
          options:
            - 1 file
            - 2-5 files
            - 5-15 files
            - 15-40 files
            - 40+ files
          required: true
        - key: epic_count_estimate
          question: How many major features/epics does this involve?
          options:
            - Just one task
            - 1 feature
            - 2-5 features
            - 5-10 features
            - 10+ features
          required: true

    - name: Assess Complexity
      type: elicit
      prompts:
        - key: team_size
          question: How many people will work on this?
          options:
            - Just me
            - 2-3 people
            - 4-6 people
            - 7+ people
          required: true
        - key: dependencies
          question: Does this project have external dependencies or integrations?
          options:
            - No external dependencies
            - 1-2 simple integrations
            - Multiple integrations
            - Complex integration architecture
          required: true
        - key: documentation_needed
          question: What level of documentation is required?
          options:
            - Just code comments
            - README + comments
            - README + API docs
            - Full documentation suite (PRD, tech specs, API docs, guides)
          required: true

    - name: Calculate Scale Level
      type: template
      template_path: templates/scale-calculation.md
      output_path: "{output_folder}/scale-assessment.md"
      variables:
        - project_name
        - project_description
        - time_estimate
        - file_count_estimate
        - epic_count_estimate
        - team_size
        - dependencies
        - documentation_needed

    - name: Recommend Next Steps
      type: guide
      content: |
        # Scale Level Determined

        Based on your answers, I'll recommend the appropriate planning approach:

        - **Level 0-1**: Fast-track - start coding immediately with minimal planning
        - **Level 2**: PRD-lite + basic epic breakdown
        - **Level 3-4**: Full PRD + tech spec + detailed epic/story breakdown

        Your scale assessment has been saved to `{output_folder}/scale-assessment.md`.

        Would you like to proceed with the recommended planning workflow?

  outputs:
    - path: "{output_folder}/scale-assessment.md"
      description: Scale level assessment and recommendations
